#!/bin/bash

#######################################
# CSUbatch Scheduling System Runner
# 
# This script runs the CSUbatch application.
#
# Usage: ./CSUbatch
#######################################

# Set working directory to script location
cd "$(dirname "$0")"

# Verify dependencies are installed
check_dependency() {
    if ! command -v $1 &> /dev/null; then
        echo "$1 is not installed. Please install $1 to run CSUbatch."
        exit 1
    fi
}

check_dependency "java"

# clear the logs directory
rm -rf logs/*

# Run the application using Java
java -cp target/classes com.project.unified.UnifiedApp